# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
en:
  languageCode: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/en
  title: 'Simplesmente Capoeira e.V.'
  params:
    description: 'Learn Capoeira in Berlin! Simplesmente Capoeira e.V. teaches Afro-Brazilian movement, acrobatics, music and martial arts for beginners, adults and kids in Schöneberg, Kreuzberg and Mitte. First month of training is free.'

# alternative language
de:
  languageCode: de-de
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/de
  title: 'Simplesmente Capoeira e.V.'
  params:
    description: 'Lerne Capoeira in Berlin! Simplesmente Capoeira e.V. unterrichtet afro-brasilianische Bewegung, Akrobatik, Musik und Kampfkunst für Anfänger, Erwachsene und Kinder in Schöneberg, Kreuzberg und Mitte. Der erste Monat Training ist kostenlos.'

# Uncomment the lines below to configure your website in a second language.
#zh:
#  languageCode: zh-Hans
#  contentDir: content/zh
#  title: Chinese website title...
#  params:
#    description: Site description in Chinese...
#  menu:
#    main:
#      - name: 传
#        url: '#about'
#        weight: 1
